# You may leave blank to use default setting, but DO NOT delete any item.
# Check default value in "src/util/config.py"

# Basic settings
log_path: "/home/miku/graph-atk/log"
data_dir: "/home/miku/graph-atk/data"
device: "cuda:0"
random_state: 3939
sample_nodes: 2
verbose: 1

# Experimental settings
attacks:
  - "nettack"
  - "random"
  - "sga"
models:
  - "gcn"
  - "gat"
  - "sgc"
surrogates:
  - "sgc"
datasets:
  - "cora"
  - "citeseer"
  - "pubmed"
skip:
  # format like [attack.model.surrogate.dataset], one per line
  # use '*' to match all.
  - "nettack.*.*.*"
